#!/usr/bin/env python3
"""
Round 3 Empirical Verification Suite - Domain 2: Sims Autonomy Loop
Verifies:
1. Navigational limit cycles & behavior thrashing under 25% utility hysteresis.
2. Unfulfillable affordance livelock via 30-tick progress watchdog and 120-tick blacklist.
3. 60-tick Lease TTL expiry rate vs spatial parcel dimensions.
"""

import math
import random
import unittest
from dataclasses import dataclass
from typing import List, Optional, Tuple, Dict

# ============================================================================
# 1. NAVIGATIONAL LIMIT CYCLES & HYSTERESIS THRASHING
# ============================================================================

@dataclass
class Affordance:
    name: str
    x: float # decimeters
    priority: float
    fatigue_cost_rate: float # fatigue generated by doing or walking to this task
    is_rest: bool = False

class NavigationAgent:
    """
    Implements Backlog Story 2.2 utility function:
    U(Task) = Priority + Alignment + Focus - StressCost - Fatigue.
    Evaluates dynamic whim switching during transit.
    """
    def __init__(self, x: float = 60.0):
        self.x = x # position in decimeters (0..120)
        self.speed = 0.4 # dm per tick
        self.fatigue = 0.10 # 0.0 .. 1.0
        self.focus = 0.80
        self.current_goal: Optional[Affordance] = None
        self.in_action_phase: bool = False
        self.switches: int = 0
        self.completed_tasks = 0

    def evaluate_task_utility(self, affordance: Affordance) -> float:
        # Distance penalty (time to reach) adds fatigue anticipation
        dist = abs(self.x - affordance.x)
        if affordance.is_rest:
            # Rest becomes much more desirable as fatigue rises
            return affordance.priority + self.fatigue * 0.8 - (dist / 200.0)
        else:
            # Heavy task utility plummets as fatigue rises
            return affordance.priority + self.focus * 0.2 - self.fatigue * 0.8 - (dist / 200.0)

    def step_tick(self, task_work: Affordance, task_rest: Affordance):
        u_work = self.evaluate_task_utility(task_work)
        u_rest = self.evaluate_task_utility(task_rest)

        HYSTERESIS = 0.25 # 25% utility threshold from GDD 3.4

        # Action phase check
        if self.current_goal is not None:
            dist = abs(self.x - self.current_goal.x)
            if dist < 2.0:
                self.in_action_phase = True
                if self.current_goal.is_rest:
                    self.fatigue = max(0.0, self.fatigue - 0.01) # resting recovers fatigue
                else:
                    self.fatigue = min(1.0, self.fatigue + 0.005) # working adds fatigue
                return

        self.in_action_phase = False

        # Transit adds physical walking fatigue
        self.fatigue = min(1.0, self.fatigue + 0.002)

        # Hysteresis decision loop during navigation
        if self.current_goal is None:
            self.current_goal = task_work if u_work >= u_rest else task_rest
            self.switches += 1
        elif self.current_goal == task_work:
            if u_rest > u_work + HYSTERESIS:
                self.current_goal = task_rest
                self.switches += 1
        elif self.current_goal == task_rest:
            if u_work > u_rest + HYSTERESIS:
                self.current_goal = task_work
                self.switches += 1

        # Move towards goal
        if self.current_goal is not None:
            if self.x < self.current_goal.x:
                self.x += self.speed
            else:
                self.x -= self.speed

class TestD2NavigationHysteresis(unittest.TestCase):
    def test_navigation_thrashing_and_hysteresis_effectiveness(self):
        print("\n--- [TEST D2.1] Comparative Whim Oscillation & Hysteresis Evaluation ---")
        
        # Test Case A: Without Hysteresis (0% threshold) under fluctuating whim utilities
        class WhimAgent:
            def __init__(self, hysteresis: float):
                self.x = 60.0
                self.speed = 0.4
                self.hysteresis = hysteresis
                self.current_goal: Optional[int] = None # 0 or 1
                self.switches = 0
                self.completed = 0

            def step(self, t: int):
                # Two whims with oscillating urge (e.g. fluctuating social need vs thirst)
                u0 = 0.70 + 0.15 * math.sin(t * 0.05)
                u1 = 0.70 + 0.15 * math.cos(t * 0.05)

                if self.current_goal is None:
                    self.current_goal = 0 if u0 >= u1 else 1
                    self.switches += 1
                elif self.current_goal == 0:
                    if u1 > u0 + self.hysteresis:
                        self.current_goal = 1
                        self.switches += 1
                elif self.current_goal == 1:
                    if u0 > u1 + self.hysteresis:
                        self.current_goal = 0
                        self.switches += 1

                # Goal 0 is at x = 10, Goal 1 is at x = 110
                target_x = 10.0 if self.current_goal == 0 else 110.0
                if abs(self.x - target_x) < 2.0:
                    self.completed += 1
                    # reset
                    self.x = 60.0
                    self.current_goal = None
                else:
                    self.x += self.speed if self.x < target_x else -self.speed

        # Run without hysteresis
        agent_no_hyst = WhimAgent(hysteresis=0.0)
        for t in range(1200):
            agent_no_hyst.step(t)

        # Run with 25% hysteresis
        agent_hyst = WhimAgent(hysteresis=0.25)
        for t in range(1200):
            agent_hyst.step(t)

        print(f"Without Hysteresis (0%): Switches = {agent_no_hyst.switches}, Tasks Completed = {agent_no_hyst.completed}")
        print(f"With 25% Hysteresis: Switches = {agent_hyst.switches}, Tasks Completed = {agent_hyst.completed}")

        # Without hysteresis, agent thrashes wildly and completes 0 tasks
        self.assertGreater(agent_no_hyst.switches, 15)
        self.assertEqual(agent_no_hyst.completed, 0)

        # With 25% hysteresis, agent suppresses small oscillations and completes tasks
        self.assertLess(agent_hyst.switches, agent_no_hyst.switches)
        self.assertGreater(agent_hyst.completed, 0)
        print("PASS: 25% utility hysteresis successfully dampens high-frequency whim oscillation,")
        print("allowing task completion compared to unmitigated thrashing.")


# ============================================================================
# 2. UNFULFILLABLE AFFORDANCE WATCHDOG LIVELOCK
# ============================================================================

class AffordanceFsmAgent:
    """Simulates 30-tick watchdog timer and 120-tick destination blacklist from GDD 3.4."""
    def __init__(self):
        self.x = 0.0 # position dm
        self.current_task: Optional[str] = None
        self.ticks_in_task = 0
        self.watchdog_counter = 0
        self.blacklist: Dict[str, int] = {} # task_name -> ticks_remaining
        self.last_distance = 1000.0
        self.task_history: List[str] = []
        self.abort_count = 0

    def step_tick(self, blocked_affordance_dist: float = 50.0):
        # 1. Update blacklist timers
        expired = []
        for task, remaining in self.blacklist.items():
            if remaining <= 1:
                expired.append(task)
            else:
                self.blacklist[task] = remaining - 1
        for task in expired:
            del self.blacklist[task]

        # 2. Evaluate utilities
        # Task A: Critical Water Well (Unreachable / Blocked path). Utility = 0.95
        # Task B: Turn Compost (Reachable, low utility). Utility = 0.40
        u_well = 0.95
        u_compost = 0.40
        HYSTERESIS = 0.25 # 25%

        # Select candidate
        candidate = None
        if "WELL" not in self.blacklist:
            candidate = "WELL"
        else:
            candidate = "COMPOST"

        # Apply hysteresis if currently working on a task
        if self.current_task is None:
            self.current_task = candidate
            self.ticks_in_task = 0
            self.watchdog_counter = 0
            self.last_distance = blocked_affordance_dist if candidate == "WELL" else 10.0
        elif self.current_task == "COMPOST" and candidate == "WELL":
            # Can switch if u_well > u_compost + 0.25 (0.95 > 0.40 + 0.25 = 0.65) -> YES!
            if u_well > u_compost + HYSTERESIS:
                self.current_task = "WELL"
                self.ticks_in_task = 0
                self.watchdog_counter = 0
                self.last_distance = blocked_affordance_dist

        self.task_history.append(self.current_task)

        # 3. Simulate execution & 30-Tick Progress Watchdog
        if self.current_task == "WELL":
            # Well is physically blocked by debris; distance NEVER decreases
            current_dist = blocked_affordance_dist # constant distance
            if current_dist >= self.last_distance:
                self.watchdog_counter += 1
            else:
                self.watchdog_counter = 0

            self.last_distance = current_dist

            # GDD 3.4 line 302:
            # "If an agent's physical distance to an objective fails to decrease over 30 consecutive ticks,
            # the task transitions to ACTION_BLOCKED. The agent steps back 1 decimeter, releases reservations,
            # blacklists the destination for 120 ticks, and re-evaluates utility."
            if self.watchdog_counter >= 30:
                self.abort_count += 1
                self.blacklist["WELL"] = 120 # Blacklist for 120 ticks
                self.current_task = None
                self.watchdog_counter = 0
        elif self.current_task == "COMPOST":
            # Compost task makes continuous progress
            self.ticks_in_task += 1

class TestD2WatchdogLivelock(unittest.TestCase):
    def test_unfulfillable_affordance_periodic_livelock(self):
        print("\n--- [TEST D2.2] Unfulfillable Affordance Watchdog Livelock Simulation ---")
        agent = AffordanceFsmAgent()

        # Run 600 ticks (20 seconds of game simulation at 30 Hz)
        for t in range(600):
            agent.step_tick(blocked_affordance_dist=50.0)

        # Count how many times the agent bounced back into the blocked well
        print(f"Simulation 600 ticks complete. Watchdog ACTION_BLOCKED triggers: {agent.abort_count}")
        
        # Analyze periodic cycle:
        # 30 ticks trying WELL -> 120 ticks doing COMPOST -> 30 ticks trying WELL -> 120 ticks COMPOST...
        # Period = 150 ticks. In 600 ticks, exactly 4 abort cycles should occur.
        self.assertEqual(agent.abort_count, 4)

        # Compute fraction of time spent futilely attempting blocked well
        well_ticks = agent.task_history.count("WELL")
        compost_ticks = agent.task_history.count("COMPOST")
        well_ratio = well_ticks / len(agent.task_history)
        print(f"Time spent in blocked WELL: {well_ticks} ticks ({well_ratio*100:.1f}%)")
        print(f"Time spent in COMPOST: {compost_ticks} ticks")

        self.assertGreater(well_ratio, 0.15, "Agent spent substantial recurring time trapped in blocked affordance livelock")
        print("CONFIRMED BUG:")
        print("The 120-tick blacklist has NO persistent failure counter or exponential backoff.")
        print("Every time the 120 ticks expire, high-utility unfulfillable affordances immediately preempt productive work,")
        print("causing a permanent 150-tick periodic livelock cycle.")


# ============================================================================
# 3. LEASE TTL EXPIRY VS SPATIAL PARCEL DIMENSIONS
# ============================================================================

class TestD2LeaseTtlExpiry(unittest.TestCase):
    def test_lease_ttl_vs_walking_speed(self):
        print("\n--- [TEST D2.3] 60-Tick Lease TTL Expiry vs Parcel Dimensions ---")
        # GDD 3.4: "Lease-Based Affordance Reservations: Workbenches, tools, and beds are reserved
        # using a 60-tick Time-to-Live (TTL) lease. If an agent fails to arrive before lease expiry,
        # the resource returns to the public pool."
        # Tick rate: 30 Hz (standard simulation tick) or 10 Hz (psychology tick).
        # Normal walking speed: 1.2 m/s = 12 dm/s.
        speed_dm_per_s = 12.0

        # Parcel sizes from GDD 4.3:
        # Suburban: 128 x 128 dm
        # Urban: 64 x 64 dm
        # Eco-Village: 96 x 96 dm
        biomes = {
            "Suburban Sprawl (128x128 dm)": 128.0,
            "Dense Urban (64x64 dm)": 64.0,
            "Eco-Village (96x96 dm)": 96.0,
        }

        # Case A: 30 Hz tick rate (standard engine physics/sim loop)
        ttl_seconds_30hz = 60 / 30.0 # 2.0 seconds
        max_dist_30hz = speed_dm_per_s * ttl_seconds_30hz # 24.0 dm = 2.4 meters

        # Case B: 10 Hz tick rate (DF Psychology & Agency loop)
        ttl_seconds_10hz = 60 / 10.0 # 6.0 seconds
        max_dist_10hz = speed_dm_per_s * ttl_seconds_10hz # 72.0 dm = 7.2 meters

        print(f"Max distance reachable in 60 ticks at 30 Hz: {max_dist_30hz:.1f} dm ({max_dist_30hz/10:.2f} m)")
        print(f"Max distance reachable in 60 ticks at 10 Hz: {max_dist_10hz:.1f} dm ({max_dist_10hz/10:.2f} m)")

        random.seed(42)
        TRIALS = 10000

        print("\nMonte Carlo Expiry Rate (10,000 random source-destination pairs per biome):")
        for name, side in biomes.items():
            expired_30hz = 0
            expired_10hz = 0
            for _ in range(TRIALS):
                x1, y1 = random.uniform(0, side), random.uniform(0, side)
                x2, y2 = random.uniform(0, side), random.uniform(0, side)
                dist = math.hypot(x2 - x1, y2 - y1)
                if dist > max_dist_30hz:
                    expired_30hz += 1
                if dist > max_dist_10hz:
                    expired_10hz += 1

            pct_30hz = (expired_30hz / TRIALS) * 100.0
            pct_10hz = (expired_10hz / TRIALS) * 100.0
            print(f"  * {name:<30}: 30 Hz Expiry = {pct_30hz:5.1f}% | 10 Hz Expiry = {pct_10hz:5.1f}%")

            # At 30 Hz, all biomes have over 65% premature lease expiry!
            self.assertGreater(pct_30hz, 65.0)

        print("\nCONFIRMED BUG:")
        print("A hardcoded 60-tick TTL lease without distance-adaptive scaling guarantees that the vast majority (>65% to >90%)")
        print("of affordance reservations expire while the agent is still walking towards them, creating severe resource race conditions.")

if __name__ == "__main__":
    unittest.main()
